import uuid,enum
from datetime import datetime
from sqlalchemy import String,Text,Boolean,DateTime,ForeignKey,JSON,Float,Enum,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base
def uid(): return str(uuid.uuid4())
class Role(str,enum.Enum): owner='owner'; admin='admin'; qa='qa'; viewer='viewer'
class TargetMode(str,enum.Enum): browser='browser'; openapi='openapi'; rest='rest'; transcript='transcript'
class RunStatus(str,enum.Enum): queued='queued'; running='running'; completed='completed'; failed='failed'
class Tenant(Base):
 __tablename__='tenants'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(200)); slug:Mapped[str]=mapped_column(String(100),unique=True,index=True); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class User(Base):
 __tablename__='users'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); email:Mapped[str]=mapped_column(String(320),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Membership(Base):
 __tablename__='memberships'; __table_args__=(UniqueConstraint('tenant_id','user_id'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); role:Mapped[Role]=mapped_column(Enum(Role)); active:Mapped[bool]=mapped_column(Boolean,default=True)
class RefreshToken(Base):
 __tablename__='refresh_tokens'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); token_hash:Mapped[str]=mapped_column(String(64),unique=True); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); revoked:Mapped[bool]=mapped_column(Boolean,default=False)
class Project(Base):
 __tablename__='projects'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(200)); description:Mapped[str]=mapped_column(Text,default=''); created_by:Mapped[str]=mapped_column(ForeignKey('users.id'))
class Target(Base):
 __tablename__='targets'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); project_id:Mapped[str]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(200)); base_url:Mapped[str]=mapped_column(Text); mode:Mapped[TargetMode]=mapped_column(Enum(TargetMode)); auth_encrypted:Mapped[str|None]=mapped_column(Text); config:Mapped[dict]=mapped_column(JSON,default=dict); discovery:Mapped[dict]=mapped_column(JSON,default=dict); created_by:Mapped[str]=mapped_column(ForeignKey('users.id'))
class Requirement(Base):
 __tablename__='requirements'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); project_id:Mapped[str]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE'),index=True); source:Mapped[str]=mapped_column(String(30)); text:Mapped[str]=mapped_column(Text); acceptance:Mapped[list]=mapped_column(JSON,default=list); authoritative:Mapped[bool]=mapped_column(Boolean,default=False)
class Run(Base):
 __tablename__='runs'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); project_id:Mapped[str]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE'),index=True); target_id:Mapped[str]=mapped_column(ForeignKey('targets.id',ondelete='CASCADE'),index=True); workflow_run_id:Mapped[str|None]=mapped_column(String(36),index=True); prompt_version_id:Mapped[str|None]=mapped_column(String(36)); created_by:Mapped[str]=mapped_column(ForeignKey('users.id')); status:Mapped[RunStatus]=mapped_column(Enum(RunStatus),default=RunStatus.queued); is_baseline:Mapped[bool]=mapped_column(Boolean,default=False); baseline_id:Mapped[str|None]=mapped_column(String(36)); score:Mapped[float|None]=mapped_column(Float); pass_rate:Mapped[float|None]=mapped_column(Float); release_gate:Mapped[str|None]=mapped_column(String(20)); risk_score:Mapped[float|None]=mapped_column(Float); hallucination_rate:Mapped[float|None]=mapped_column(Float); release_confidence:Mapped[float|None]=mapped_column(Float); summary:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Result(Base):
 __tablename__='results'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); run_id:Mapped[str]=mapped_column(ForeignKey('runs.id',ondelete='CASCADE'),index=True); case_type:Mapped[str]=mapped_column(String(40)); prompt:Mapped[str]=mapped_column(Text); response:Mapped[str]=mapped_column(Text,default=''); evidence:Mapped[dict]=mapped_column(JSON,default=dict); rule_score:Mapped[float]=mapped_column(Float); safety_score:Mapped[float]=mapped_column(Float); business_score:Mapped[float|None]=mapped_column(Float); composite_score:Mapped[float]=mapped_column(Float); passed:Mapped[bool]=mapped_column(Boolean); rationale:Mapped[list]=mapped_column(JSON,default=list); requirement_id:Mapped[str|None]=mapped_column(String(20)); use_case_id:Mapped[str|None]=mapped_column(String(20)); scenario_id:Mapped[str|None]=mapped_column(String(20))
class Audit(Base):
 __tablename__='audit'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); user_id:Mapped[str]=mapped_column(String(36)); action:Mapped[str]=mapped_column(String(100)); resource:Mapped[str]=mapped_column(String(100)); resource_id:Mapped[str|None]=mapped_column(String(36)); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())

class PolicyCategory(str,enum.Enum): pii='pii'; security='security'; compliance='compliance'; responsible_ai='responsible_ai'
class Severity(str,enum.Enum): low='low'; medium='medium'; high='high'; critical='critical'

class PromptVersion(Base):
 """Prompt/config governance: every generator/system-prompt or target config change is versioned and auditable."""
 __tablename__='prompt_versions'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); target_id:Mapped[str]=mapped_column(ForeignKey('targets.id',ondelete='CASCADE'),index=True); version_no:Mapped[int]=mapped_column(default=1); system_prompt:Mapped[str]=mapped_column(Text,default=''); config_snapshot:Mapped[dict]=mapped_column(JSON,default=dict); notes:Mapped[str]=mapped_column(Text,default=''); active:Mapped[bool]=mapped_column(Boolean,default=True); created_by:Mapped[str]=mapped_column(ForeignKey('users.id')); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())

class PolicyRule(Base):
 """Governance/compliance/PII/security/responsible-AI rule enforced on every result during evaluation."""
 __tablename__='policy_rules'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); project_id:Mapped[str]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(200)); category:Mapped[PolicyCategory]=mapped_column(Enum(PolicyCategory)); pattern:Mapped[str]=mapped_column(Text,default=''); description:Mapped[str]=mapped_column(Text,default=''); severity:Mapped[Severity]=mapped_column(Enum(Severity),default=Severity.medium); built_in:Mapped[bool]=mapped_column(Boolean,default=False); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())

class PolicyFinding(Base):
 """A single governance violation surfaced against a result (PII leak, banned phrase, security/compliance breach)."""
 __tablename__='policy_findings'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); run_id:Mapped[str]=mapped_column(ForeignKey('runs.id',ondelete='CASCADE'),index=True); result_id:Mapped[str]=mapped_column(ForeignKey('results.id',ondelete='CASCADE'),index=True); rule_id:Mapped[str|None]=mapped_column(String(36)); rule_name:Mapped[str]=mapped_column(String(200)); category:Mapped[PolicyCategory]=mapped_column(Enum(PolicyCategory)); severity:Mapped[Severity]=mapped_column(Enum(Severity)); detail:Mapped[str]=mapped_column(Text,default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())

class Workflow(Base):
 """Ordered chain of targets validated as one end-to-end multi-agent enterprise workflow."""
 __tablename__='workflows'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); project_id:Mapped[str]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(200)); description:Mapped[str]=mapped_column(Text,default=''); steps:Mapped[list]=mapped_column(JSON,default=list); created_by:Mapped[str]=mapped_column(ForeignKey('users.id')); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())

class WorkflowRun(Base):
 __tablename__='workflow_runs'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); workflow_id:Mapped[str]=mapped_column(ForeignKey('workflows.id',ondelete='CASCADE'),index=True); created_by:Mapped[str]=mapped_column(ForeignKey('users.id')); status:Mapped[RunStatus]=mapped_column(Enum(RunStatus),default=RunStatus.queued); run_ids:Mapped[list]=mapped_column(JSON,default=list); composite_score:Mapped[float|None]=mapped_column(Float); release_gate:Mapped[str|None]=mapped_column(String(20)); summary:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())

class Certificate(Base):
 """Tamper-evident release certificate binding a target+prompt version to run evidence."""
 __tablename__='certificates'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); target_id:Mapped[str]=mapped_column(ForeignKey('targets.id',ondelete='CASCADE'),index=True); run_id:Mapped[str]=mapped_column(ForeignKey('runs.id',ondelete='CASCADE'),index=True); prompt_version_id:Mapped[str|None]=mapped_column(String(36)); status:Mapped[str]=mapped_column(String(20)); payload:Mapped[dict]=mapped_column(JSON,default=dict); signature:Mapped[str]=mapped_column(String(64)); issued_by:Mapped[str]=mapped_column(ForeignKey('users.id')); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())

class MonitorSample(Base):
 """A production/staging interaction sampled back into AVaaS for continuous validation."""
 __tablename__='monitor_samples'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); target_id:Mapped[str]=mapped_column(ForeignKey('targets.id',ondelete='CASCADE'),index=True); prompt:Mapped[str]=mapped_column(Text); response:Mapped[str]=mapped_column(Text,default=''); rule_score:Mapped[float|None]=mapped_column(Float); policy_findings:Mapped[list]=mapped_column(JSON,default=list); passed:Mapped[bool]=mapped_column(Boolean,default=False); source:Mapped[str]=mapped_column(String(30),default='production'); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())

class RequirementAnalysis(Base):
 """Versioned output of the Requirement & Use Case Analysis Engine for a project.
 Structured use cases, source-classified requirements, user intents, test-scenario
 stubs, and requirement gaps — the traceable spec the test generator consumes."""
 __tablename__='requirement_analyses'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); project_id:Mapped[str]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE'),index=True); version_no:Mapped[int]=mapped_column(default=1); inputs:Mapped[dict]=mapped_column(JSON,default=dict); analysis:Mapped[dict]=mapped_column(JSON,default=dict); llm_provider:Mapped[str]=mapped_column(String(20),default=''); created_by:Mapped[str]=mapped_column(ForeignKey('users.id')); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
