import uuid,enum
from datetime import datetime
from sqlalchemy import String,Text,Boolean,DateTime,ForeignKey,JSON,Float,Enum,UniqueConstraint,func
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base
def uid(): return str(uuid.uuid4())
class Role(str,enum.Enum): owner='owner'; admin='admin'; qa='qa'; viewer='viewer'
class TargetMode(str,enum.Enum): browser='browser'; openapi='openapi'; rest='rest'; transcript='transcript'
class RunStatus(str,enum.Enum): queued='queued'; running='running'; completed='completed'; failed='failed'
class Tenant(Base):
 __tablename__='tenants'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(200)); slug:Mapped[str]=mapped_column(String(100),unique=True,index=True); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class User(Base):
 __tablename__='users'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); email:Mapped[str]=mapped_column(String(320),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Membership(Base):
 __tablename__='memberships'; __table_args__=(UniqueConstraint('tenant_id','user_id'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); role:Mapped[Role]=mapped_column(Enum(Role)); active:Mapped[bool]=mapped_column(Boolean,default=True)
class RefreshToken(Base):
 __tablename__='refresh_tokens'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); user_id:Mapped[str]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); token_hash:Mapped[str]=mapped_column(String(64),unique=True); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); revoked:Mapped[bool]=mapped_column(Boolean,default=False)
class Project(Base):
 __tablename__='projects'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(200)); description:Mapped[str]=mapped_column(Text,default=''); created_by:Mapped[str]=mapped_column(ForeignKey('users.id'))
class Target(Base):
 __tablename__='targets'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); project_id:Mapped[str]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(200)); base_url:Mapped[str]=mapped_column(Text); mode:Mapped[TargetMode]=mapped_column(Enum(TargetMode)); auth_encrypted:Mapped[str|None]=mapped_column(Text); config:Mapped[dict]=mapped_column(JSON,default=dict); discovery:Mapped[dict]=mapped_column(JSON,default=dict); created_by:Mapped[str]=mapped_column(ForeignKey('users.id'))
class Requirement(Base):
 __tablename__='requirements'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); project_id:Mapped[str]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE'),index=True); source:Mapped[str]=mapped_column(String(30)); text:Mapped[str]=mapped_column(Text); acceptance:Mapped[list]=mapped_column(JSON,default=list); authoritative:Mapped[bool]=mapped_column(Boolean,default=False)
class Run(Base):
 __tablename__='runs'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),index=True); project_id:Mapped[str]=mapped_column(ForeignKey('projects.id',ondelete='CASCADE'),index=True); target_id:Mapped[str]=mapped_column(ForeignKey('targets.id',ondelete='CASCADE'),index=True); created_by:Mapped[str]=mapped_column(ForeignKey('users.id')); status:Mapped[RunStatus]=mapped_column(Enum(RunStatus),default=RunStatus.queued); is_baseline:Mapped[bool]=mapped_column(Boolean,default=False); baseline_id:Mapped[str|None]=mapped_column(String(36)); score:Mapped[float|None]=mapped_column(Float); pass_rate:Mapped[float|None]=mapped_column(Float); release_gate:Mapped[str|None]=mapped_column(String(20)); summary:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Result(Base):
 __tablename__='results'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); run_id:Mapped[str]=mapped_column(ForeignKey('runs.id',ondelete='CASCADE'),index=True); case_type:Mapped[str]=mapped_column(String(40)); prompt:Mapped[str]=mapped_column(Text); response:Mapped[str]=mapped_column(Text,default=''); evidence:Mapped[dict]=mapped_column(JSON,default=dict); rule_score:Mapped[float]=mapped_column(Float); safety_score:Mapped[float]=mapped_column(Float); business_score:Mapped[float|None]=mapped_column(Float); composite_score:Mapped[float]=mapped_column(Float); passed:Mapped[bool]=mapped_column(Boolean); rationale:Mapped[list]=mapped_column(JSON,default=list)
class Audit(Base):
 __tablename__='audit'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); user_id:Mapped[str]=mapped_column(String(36)); action:Mapped[str]=mapped_column(String(100)); resource:Mapped[str]=mapped_column(String(100)); resource_id:Mapped[str|None]=mapped_column(String(36)); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
